---
title: "Untitled"
format: html
---



https://bioconductor.org/packages/release/bioc/vignettes/TCGAbiolinks/inst/doc/casestudy.html#Case_study_n_1:_Pan_Cancer_downstream_analysis_BRCA

```{r}
# BiocManager::install("TCGAbiolinks")
library(TCGAbiolinks)
library(SummarizedExperiment)
library(dplyr)

# Check how many TCGA cancer datasets do we have
projects = getGDCprojects()
tcga_projects = projects[grep("^TCGA-", projects$project_id), ]
tcga_projects %>% openxlsx::write.xlsx("../data/TCGA/TCGA_projects.xlsx")
cancer_types = tcga_projects$tumor
cancer_types
#  [1] "BRCA" "UCEC" "LAML" "CHOL" "ACC"  "DLBC" "CESC" "ESCA" "KICH" "HNSC"
# [11] "COAD" "BLCA" "KIRP" "GBM"  "MESO" "SARC" "PCPG" "READ" "LUAD" "LUSC"
# [21] "PAAD" "LIHC" "KIRC" "LGG"  "SKCM" "PRAD" "STAD" "OV"   "THYM" "UCS" 
# [31] "UVM"  "TGCT" "THCA"

test = GDCquery(
  project = "TCGA-LAML",
  data.category = "Transcriptome Profiling",
  data.type = "Gene Expression Quantification"
)
getResults(test) %>% head()

# 🔁 Loop through each cancer type
for (cancer in setdiff(cancer_types,c("BLCA", "KIRP", "LGG"))) {
    cat("Downloading data for:", cancer, "\n")
    cancer_path = paste0("../data/TCGA/", cancer,"/")
    if (!dir.exists(cancer_path)) {
        # Query
        query = GDCquery(project = paste0("TCGA-", cancer),
                        data.category = "Transcriptome Profiling",
                        data.type = "Gene Expression Quantification",
                        workflow.type = "STAR - Counts",
                        sample.type = c("Primary Tumor", "Solid Tissue Normal"))
        if (!is.null(query)) {
            results = getResults(query)           
            results %>% openxlsx::write.xlsx(.,paste0("Meta_", cancer,".xlsx"))
            clinical = GDCquery_clinic(project = paste0("TCGA-", cancer), type = "clinical") 
            clinical[,sapply(clinical, function(col) is.atomic(col) && !is.list(col))] %>%
                openxlsx::write.xlsx(., paste0("Clinical_", cancer,".xlsx"))
            
            # Download
            GDCdownload(query, files.per.chunk = 100, method = "api")

            # Move the output folder and result to cancer_path
            cancer_path %>% dir.create(., recursive=T, showWarnings=F)
            from_files = list.files("./", pattern="*.tar.gz|*.txt|*xlsx", full.names = TRUE)
            lapply(from_files, function(from) {
                file.rename(from = from,
                        to   = paste0(cancer_path, "/", from))
            })
            file.rename(from = "GDCdata",
                        to   = paste0(cancer_path, "/GDCdata"))
        }
    }
}

# TCGA-BLCA problematic

```




```{r}
# BiocManager::install("TCGAbiolinks")
library(SummarizedExperiment)
library(TCGAbiolinks)
library(dplyr)
# Query TCGA for liver hepatocellular carcinoma (LIHC)
query.exp = GDCquery(
    project = "TCGA-BRCA", 
    data.category = "Transcriptome Profiling",
    data.type = "Gene Expression Quantification", 
    workflow.type = "STAR - Counts",
    sample.type = c("Primary Tumor","Solid Tissue Normal"))
getResults(query.exp) %>% 
    openxlsx::write.xlsx(paste0("Meta_", cancer,".xlsx"))
GDCquery_clinic(project = "TCGA-BRCA", type = "clinical") %>% 
    openxlsx::write.xlsx(paste0("Clinical_", cancer,".xlsx"))



GDCdownload(
    query = query.exp,
    files.per.chunk = 100)



table(clinical$classification_of_tumor)
dim(clinical)
"7bcb3817-31ac-4ef5-9038-a9bfebad5869" %in% clinical$treatments_radiation_treatment_id
"7bcb3817-31ac-4ef5-9038-a9bfebad5869" %in% clinical$diagnosis_id

brca.exp = GDCprepare(
    query = query.exp
    #save = TRUE, 
    # save.filename = "brcaExp.rda",
    # summarizedExperiment = TRUE
)
# Extract counts
counts = assay(brca.exp)

# get subtype information
infomation.subtype <- TCGAquery_subtype(tumor = "BRCA")

# get clinical data
information.clinical <- GDCquery_clinic(project = "TCGA-BRCA",type = "clinical") 

# Which samples are Primary Tumor
samples.primary.tumour <- brca.exp$barcode[brca.exp$shortLetterCode == "TP"]

# which samples are solid tissue normal
samples.solid.tissue.normal <- brca.exp$barcode[brca.exp$shortLetterCode == "NT"]

```