---
title: "SMTdb_cancer: nonMalignant vs Malignant spots"
author: Yuan Li (yuan.li@nbis.se)
format: html
---



Here we compare the Malignant vs nonMalignant spots in the spatial transcriptomics data.

```{r}
# BiocManager::install("TCGAbiolinks")
library(TCGAbiolinks)
library(SummarizedExperiment)
library(dplyr)
library(dplyr)
library(ggplot2)
library(parseMetab)
# remove.packages("parseMetab")
# detach("package:KinaseDownstream", unload = TRUE)
# remotes::install_github("Maj18/parseMetab", dependencies = TRUE)
# library(parseMetab)
```

# Download SMTdb cancer slice data

```{bash}
# #!/bin/bash

# (
#   echo -e "cancer\ttissue\tpaper\tpaper_html\tdatasetID\tspot_num\tcell_num\tbac_num\tslice_type\tsample"
#   jq -r '
#     .data[] | [
#       .cancer,
#       .tissue,
#       .paper,
#       .paper_html,
#       .datasetID,
#       .spot_num,
#       .cell_num,
#       .bac_num,
#       .slice_type,
#       .sample
#     ] | @tsv
#   ' ../data/SMTdb/download_file.json
# ) > ../data/SMTdb/output.tsv

# # First get the header to know column numbers
# header=$(head -1 ../data/SMTdb/output.tsv)

# # Example columns based on your JSON (adjust if different):
# # cancer = column 1
# # datasetID = column 5
# # slice_type = column 9

# # List of files to download
# files=("st_cluster.txt" "st_neb.txt" "st_dev_rctd.txt" "st_gene_exp_count.txt")

# tail -n +2 ../data/SMTdb/output.tsv | awk -F '\t' '$9 == "cancer" { print $1 "\t" $5 }' | while IFS=$'\t' read -r cancer dataset_id; do
#   mkdir -p "../data/SMTdb/$cancer"/${dataset_id}

#   for file in "../data/SMTdb/${files[@]}"; do
#     output_file="../data/SMTdb/${cancer}/${dataset_id}/${file}"
#     if [ -f "$output_file" ]; then
#       echo "File $output_file already exists, skipping download."
#     else
#       echo "Downloading $file for $dataset_id into folder $cancer"
#       curl -L -o "$output_file" "http://bio-bigdata.hrbmu.edu.cn/SMTdb/downloadCopy.jsp?filename=${file}&loc=${dataset_id}"
#     fi
#   done

# done

```

# Process the data

## Import data

```{r}
#' Import SMTdb files
#' 
#' Import SMTdb files for all cancer types and all slides.
#' 
#' @param INDIR Directory where the SMTdb files are placed, it shoud be organized as <Cancer_type>/<Sample_ID>/*.txt.
#' @param pattern What files to import, e.g. "st_neb.txt".
#' 
#' @return A list of list of tables:
#'  The first level of lists contains all cancer types.
#'  The second level of lists contains all slices within each cancer type.
#'
#' @examples 
#' # importFiles_SMTdb(INDIR, pattern="st_gene_exp_count.txt")
#' 
importFiles_SMTdb = function(INDIR, pattern="st_gene_exp_count.txt") {
    cancers = list.dirs(INDIR, full.names=FALSE, recursive=FALSE)
    lapply(cancers, function(cancer) {
        cancer_dir = paste0(INDIR, "/", cancer, "/")
        file_paths = 
            list.files(cancer_dir, 
            pattern=pattern, full.names=TRUE, recursive=TRUE)
        file_samples = list.dirs(cancer_dir, full.names=F, recursive=FALSE)
        dat = lapply(file_paths, function(file) {
            read.table(file, header = TRUE, 
                sep = "\t", stringsAsFactors = FALSE, row.names = NULL) %>%
            as.data.frame() 
        }) %>% setNames(file_samples)
    }) %>% setNames(cancers)
}

INDIR = "../data/SMTdb/"
SpatialNeighborhood = importFiles_SMTdb(INDIR, pattern="st_neb.txt")
STexpr = importFiles_SMTdb(INDIR, pattern="st_gene_exp_count.txt")

# Save the objects
OUTDIR = "../results/SMTdb_cancer/"
OUTDIR %>% dir.create(., recursive=TRUE, showWarnings=FALSE)
saveRDS(SpatialNeighborhood, paste0(OUTDIR, "/SpatialNeighborhood.RDS"))
# SpatialNeighborhood = readRDS(paste0(OUTDIR, "/SpatialNeighborhood.RDS"))
saveRDS(STexpr, paste0(OUTDIR, "/STexpr.RDS"))
# STexpr = readRDS(paste0(OUTDIR, "/STexpr.RDS"))
```

## Make pseudo-bulk per slice

```{r}
#' Make pseudobulk data from spatial transcriptomics data.
#' 
#' Aggregate the gene count across all Malignant/Non-malignant spots for each cancer slide.
#' 
#' @param SpatialNeighborhood The spatial neighborhood data got with importFiles_SMTdb().
#' @param STexpr The spatial transcriptomcis expression data got with importFiles_SMTdb().
#' 
#' @return A list of pseudobulk RNA counts, with each component represent a cancer type.
#' 
#' @examples 
#' # getPseudoBulk(SpatialNeighborhood, STexpr)
#' 
getPseudoBulk = function(SpatialNeighborhood, STexpr) {
    lapply(names(SpatialNeighborhood), function(cancer) {
        print(cancer)
        sp_nei = SpatialNeighborhood[[cancer]]
        st_expr = STexpr[[cancer]]
        lapply(names(sp_nei), function(sample) {
            sp_nei_sample = sp_nei[[sample]] %>% na.omit() 
            st_expr_sample = st_expr[[sample]] %>% na.omit() %>%
                tibble::column_to_rownames(var="row.names")
            st_expr_sample = st_expr_sample[rowSums(st_expr_sample, na.rm=T)>1,]
            st_expr_sample = st_expr_sample[, colSums(st_expr_sample, na.rm=T)>0]
            Malignant_spots = sp_nei_sample %>% 
                filter(Location%in%c("Malignant", "Mal")) %>% pull(row.names) %>%
                gsub("-", ".", .) %>%
                intersect(., colnames(st_expr_sample))
            Non_malignant_spots = sp_nei_sample %>% 
                filter(Location%in%c("Non-malignant", "nMal")) %>% pull(row.names) %>%
                gsub("-", ".", .) %>%
                intersect(., colnames(st_expr_sample))
                # we only keep cancers with at least 3 slides
            if (length(Malignant_spots)>=3) {
                Malignant =  rowSums(st_expr_sample[, Malignant_spots], na.rm=T)} else {
                    Malignant = NA
                }
                # we only keep cancers with at least 3 slides
            if (length(Non_malignant_spots)>=3) {
                Non_malignant =  rowSums(st_expr_sample[, Non_malignant_spots], na.rm=T)} else {
                    Non_malignant = NA
                }
            data.frame(Feature=rownames(st_expr_sample),
                Malignant =  Malignant,
                Non_malignant = Non_malignant
            ) %>% setNames(c("Feature", paste0(c("Malignant", "nonMalignant"), "_", sample)))
        }) %>% Reduce(full_join, .)
    }) %>% setNames(names(SpatialNeighborhood))
}

pseudoBulk = getPseudoBulk(SpatialNeighborhood, STexpr)
head(pseudoBulk[["EC"]])
# Filter out undetected features and cancers with less than 6 samples:
pseudoBulk = lapply(names(pseudoBulk), function(cancer) {
    print(cancer)
    dat = pseudoBulk[[cancer]]
    dat = dat[, c(TRUE, colSums(dat[,2:ncol(dat)], na.rm=T)>0), drop=FALSE]
    dat[rowSums(dat[, 2:ncol(dat), drop=FALSE], na.rm=T)>0, ]
    if (ncol(dat)>8) {
        dat
    } else {NA}
}) %>% setNames(names(pseudoBulk))

pseudoBulk = pseudoBulk[!is.na(pseudoBulk)]

# We ony keep cancer that at least have 2 values in each group (Malignant vs nonMalignant)
pseudoBulk = lapply(pseudoBulk, function(pb) {
    nonMal = grep("nonMalignant", colnames(pb), value=T)
    Mal = setdiff(colnames(pb), c("Feature", nonMal))
    if (length(nonMal)>2&length(Mal)>=2) {
        pb
    } else {NA}
}) %>% .[!is.na(.)]

saveRDS(pseudoBulk, paste0(OUTDIR, "/pseudoBulk.RDS"))
# pseudoBulk = readRDS(paste0(OUTDIR, "/pseudoBulk.RDS"))
openxlsx::write.xlsx(pseudoBulk, 
    file=paste0(OUTDIR, "/PseudoCount_filtered.xlsx"))

rm(SpatialNeighborhood, STexpr)
gc()

```


# GSVA metabolic differential analysis

## Get KEGG metabolic pathways

```{r}
# Get KEGG metabolic pathways
paste0(OUTDIR, "/KEGG_metabolism/") %>% 
    dir.create(., recursive=TRUE, showWarnings=FALSE)

kegg_metab_dbs = 
    getdb_metabolism(databaseDIR=paste0(OUTDIR, "/KEGG_metabolism/"))

kegg_metab_db = kegg_metab_dbs$kegg_metab_db

# databaseDIR=paste0(OUTDIR, "/KEGG_metabolism/")
# kegg_metab_dbs = 
# list(kegg_metab_db = readRDS(paste0(databaseDIR, "/KEGG_metabolism_db.RDS")),
#     kegg_metab_db_table = readRDS(paste0(databaseDIR, "/KEGG_metabolism_db_table.RDS")))

# Make a circular packing plot to show the number of pathways in each class
getCirPackingPlot_GSVA(
    kegg_metab_db_table = kegg_metab_dbs$kegg_metab_db_table,
    outdir = OUTDIR)

```

## Paired differential analysis on sample GSVA scores

```{r}
OUTDIR = "../results/SMTdb_cancer/"
GSVA_limma_rslt = lapply(names(pseudoBulk), function(cancer) {
    print(cancer)
    dat = pseudoBulk[[cancer]] 
    rownames(dat) = NULL
    dat = dat %>% as.data.frame() %>%
        tibble::column_to_rownames(var="Feature") %>% na.omit()
    meta = data.frame(Slide = colnames(dat) %>% 
                gsub("nonMalignant_", "", .) %>%
                gsub("Malignant_", "", .),
            Group = gsub("_.*", "", colnames(dat)),
            Sample = colnames(dat))
    meta$Group = factor(meta$Group, levels=c("nonMalignant", "Malignant")) # Reference first!
    paste0(OUTDIR, "/Limma_GSVA/", cancer, "/") %>%
        dir.create(., recursive=TRUE, showWarnings=FALSE)
    GSVAlimmaTest(dat, paired=TRUE, Feature.filtering=TRUE,
        currentCovariate=NULL, meta=meta, paired_variable="Slide", 
        kegg_metab_db=kegg_metab_dbs$kegg_metab_db, 
        OUTDIR=paste0(OUTDIR, "/Limma_GSVA/", cancer, "/"),
        min.count=5)
}) %>% setNames(names(pseudoBulk))

GSVA_limma_rslt = 
    GSVA_limma_rslt[sapply(GSVA_limma_rslt, function(g) {is.data.frame(g$gsva)})]

saveRDS(GSVA_limma_rslt, 
    paste0(OUTDIR, "/Limma_GSVA/GSVAlimma_rslt_all.RDS"))

# GSVA_limma_rslt = readRDS(paste0(outdir, "/Limma_GSVA/GSVAlimma_rslt_all.RDS"))
```

## Visualize differential results

```{r}
rlst_list = lapply(GSVA_limma_rslt, function(l) l$rslt_of_interest)
makeLimmaDotplot_TCGA(rlst_list, adj.P.Val.cutoff=0.2, w=8, h=8, 
        OUTDIRV = paste0(OUTDIR, "/Limma_GSVA/"), Depth="gs_name", 
        lowfigure=F, title = "Dys.Path_SMTdb", 
        suffix="SMTdb", nested=T,
        taskHierarchy=kegg_metab_dbs$kegg_metab_db_table %>% 
                            select(gs_name, class) %>% unique())

# temp = as.data.frame(GSVA_limma_rslt[["OSCC"]]$gsva)["Linoleic acid metabolism",] 
# temp[, grep("nonMalignant", colnames(temp))]  %>% as.numeric() %>% mean()
# temp[, !grepl("nonMalignant", colnames(temp))]  %>% as.numeric() %>% mean()                    

```



```{r}
# save.image(paste0(OUTDIR, "/SMTdb_cancer.RData"))
# load(paste0(outdir, "/TCGA.RData"))
out = capture.output(sessionInfo())
writeLines(out, paste0(OUTDIR, "/sessionInfo.txt"))

```
